FROM python:3.11-slim
WORKDIR /app
COPY requirements-base.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY flight_service/main.py .
EXPOSE 8002
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8002"]
